### ISSUE TITLE
LAB: Working with Ansible Roles

### ISSUE THREAD

**Issue by francsw** [francsw/EX407-Ansible-Automation#8]
- [x] Create web install playbook.
- [x]   Create the necessary directories and files for the baseline role.
- [x]     Configure the role to deploy the /etc/motd template.
- [x]     Configure the role to install the latest Nagios client.
- [x]     Configure the role to add an entry to /etc/hosts for the Nagios server.
- [x]     Configure the role to create the noc user and deploy the provided public key for the noc user on target systems (copy authorized_keys to /home/noc/.ssh authorized_keys with the owner and group owner set as noc and the mode as 0600).
- [x]     Edit web.yml to deploy the baseline role in addition to what it already does.
- [x]     Verify that your role works by deploying web.yml with Ansible.

**Comment by francsw** [comment]
ansible-galaxy init ./roles/baseline

```
---
# tasks file for ./roles/baseline

- name: MOTD template
  copy:
    src: motd
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644

- name: Add and enable EPEL repo
  package:
    name: epel-release.noarch
    state: latest

- name: Install the nagios plugin
  package:
    name: nagios-common
    state: latest

- name: Add Nagios server to hosts file
  lineinfile:
    path: /etc/hosts
    line: "192.168.60.123 nagios.lab.local"
    state: present

- name: Create users
  user:
    name: noc
    create_home: yes
    generate_ssh_key: yes

- name: Copy auth keys
  copy:
    src: authorized_keys_noc
    dest: /home/noc/.ssh/authorized_keys
    owner: noc
    group: noc
    mode: 0600
```
Create files in ./roles/baseline/files/motd and authorized_keys
